### PR TITLE
Improve model check speed

### PR DESCRIPTION
**Pull request by thetumbled**
Improve model check speed by enabling symmetry set.

### CODE REVIEW

**Comment by thetumbled** [comment]
As we don't check the liveness of the spec, we can use symmetry set to speed up the model check sinificantly.
Though i have run the BookKeeperProtocol.tla for almost two days, the check process is not completed still. 
Ideally, this pr could reduce state space by 4!*2!=48 times.

PS: May i ask how much time do you take to complete the model check for BookKeeperProtocol.tla without optimization above? and how big the state space really is? thanks. @Vanlightly

**Comment by Vanlightly** [comment]
First of all, thanks for the PRs!

I always used to use the Toolbox to actually run the spec, so I always set up symmetry there. I put the cfg for people using VS Code. However, seeing as the VS Code plugin has improved a lot since, I'm using the plugin more now, so this PR helps there thank you!

The size of the state space I don't remember, it's been 3 years since I wrote this. I have been meaning to update the message passing logic and liveness logic. I have new ways of modelling message passing that reduces the state space significantly, and have adopted liveness checking a lot more (which would have caught the fragment metadata bug). For now, out of curiosity, I'll get my workstation to run this with and without symmetry for a small model (1 value, WQ=3, AQ=2, 3 bookies), and see how big the state space is for that model.

**Comment by thetumbled** [comment]
> First of all, thanks for the PRs!
> 
> I always used to use the Toolbox to actually run the spec, so I always set up symmetry there. I put the cfg for people using VS Code. However, seeing as the VS Code plugin has improved a lot since, I'm using the plugin more now, so this PR helps there thank you!
> 
> The size of the state space I don't remember, it's been 3 years since I wrote this. I have been meaning to update the message passing logic and liveness logic. I have new ways of modelling message passing that reduces the state space significantly, and have adopted liveness checking a lot more (which would have caught the fragment metadata bug). For now, out of curiosity, I'll get my workstation to run this with and without symmetry for a small model (1 value, WQ=3, AQ=2, 3 bookies), and see how big the state space is for that model.

I run the spec in server remotely, so i have to configure the cfg file. But i have already run the spec for 4 days(because i use four bookies), the progress reach to check 30-steps behaviours now. 
It seems that i have to reduce the state space much more, could you share some points about it? thanks!

**Comment by Vanlightly** [comment]
I just completed a model checking run with symmetry, 4 bookies, WQ=3, AQ=2, 1 value and 2 clients. With 22 workers and 100 GB memory, it took 142 hours (~6 days), 5,874,362,486 unique states with a diameter of 42. The maximum disk space it used was around 500 GB.

There is a technique we can use to further reduce the state space, but it will need some care. In other specs I have now switched to a set for undelivered messages and a set for delivered/dropped messages. The second set goes into a view so it doesn't contribute to the state space. This can reduce the state space massively. However, this could break this spec as it is now. For one, send checks a message wasn't sent before. It also uses a trick of using -1 delivery counts to identify lost messages. Any changes to the messages logic will need to not break how it works now. I will have a look at the work required to do this.

**Pull request merged**
